name: Trigger auto deployment for githubrepro

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/githubrepro-AutoDeployTrigger-bfed6c5d-97ec-4039-976f-b1ea393792bf.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: layliuregistry.azurecr.io
          username: ${{ secrets.GITHUBREPRO_REGISTRY_USERNAME }}
          password: ${{ secrets.GITHUBREPRO_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: layliuregistry.azurecr.io/githubrepro:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GITHUBREPRO_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n githubrepro -g layliu --server layliuregistry.azurecr.io --username  ${{ secrets.GITHUBREPRO_REGISTRY_USERNAME }} --password ${{ secrets.GITHUBREPRO_REGISTRY_PASSWORD }}
            az containerapp update -n githubrepro -g layliu --image layliuregistry.azurecr.io/githubrepro:${{ github.sha }}
